### ISSUE TITLE
20200522: Ensure one fastq set per lane index

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/ingest-graph-validator#11]
**Describe the issue**

As a data wrangler, I would like to test the integrity of the dataset I'm wrangling by ensuring that not more than one set of fastq files is assigned to one lane index. This could extend the `ensure_lane_index` test or be created as a new test. 

Specifically I would like the test to ensure that only one read1, read2, index1, index2 occurs within one lane index of one library prep.

**Test template**

- Test name: Ensure one fastq set per lane index
- Test Description: This test ensures that there is a one-to-one relationship between read index and lane index. Within one library prep there can only be one read1, read2, index1, index2 per lane.

- Cypher query:
I don't know cypher but attempt at pseudo code
```
For each library prep
    For each lane index
        count of read index type should be =< 1
```

** Acceptance criteria**

- [ ] The test has been reviewed
- [ ] The test has been implemented into the `graph_test_set` folder

**Comment by ESapenaVentura** [comment]
https://github.com/ebi-ait/ingest-graph-validator/pull/36

I have done something similar that I think also solves #31 and #30 

The query concatenates process_id, lane_index and read_index, creating a combination that should always be unique.

Then counts how many distinct files within each of these combinations and returns process_id, number of files and an error message if that number is above 1

**Comment by ESapenaVentura** [comment]
@ami-day tagging you here because I think this also solves your tickets

**Comment by ESapenaVentura** [comment]
Will be done soon :)
