### ISSUE TITLE
False errors by 10x_has_more_than_2_files.adoc

### ISSUE THREAD

**Issue by rays22** [ebi-ait/ingest-graph-validator#13]
**Describe the bug**
The rule has to take into account both the lane and the process id. i.e. there should be 2-4 files per lane per process, otherwise it produces false errors.
Also, give a more informative error message than an array of `num_files`.

**To Reproduce**
1. Use submission `85e72912-9f91-4489-8169-3b43cc65a16a`. https://github.com/HumanCellAtlas/hca-data-wrangling/issues/356
2. Hydrate and run a validation test.
3. Check the validation test output for errors.
>[ingest_graph_validator.actions.test_action] - ERROR: test [10x_has_more_than_2_files.adoc] failed: non-empty result.
[ingest_graph_validator.actions.test_action] - ERROR: result: [{'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, {'num_files': 6}, ...

**Expected behavior**
No errors for dataset `85e72912-9f91-4489-8169-3b43cc65a16a`. 

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS: all
 - Version: 0.5.4; master#7 commit 5bcb088b1ce3e493c3d22fdb91d2db53345c1b23

**Comment by mshadbolt** [comment]
I think this needs to account for the lane index in the test in order to be more accurate. As in
- For any process that uses a 10X library,
- group the process by lane index
- then perform check for at least 2 but not more than 4 files

**Comment by ESapenaVentura** [comment]
This is solved by changing the test to check for only 2+ files, and expecting if we get more than expected (e.g. 5) will be captured by "ensure_lane_index"
