### ISSUE TITLE
2020/09/07: file_format_in_file_name

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/ingest-graph-validator#16]
**Describe the issue**

As a data wrangler, I would like to test whether the file extension provided in the field "file_format" matches the file name provided in the metadata.

**Test template**

- Test name: file_format_in_file_name
- Test Description: Test whether file format is present in the name of the file.
- Cypher query:
```
MATCH (f:sequence_file)
WHERE NOT f.`file_core.file_name` ENDS WITH f.`file_core.format`
return f.`file_core.file_name`, "File format doesn't match filename"
```

** Acceptance criteria**

- [ ] The test has been reviewed
- [ ] The test has been implemented into the `graph_test_set` folder

**Comment by ami-day** [comment]
Created a pull request for the implementation of the new test here: https://github.com/ebi-ait/ingest-graph-validator/pull/17
