### ISSUE TITLE
Is test file_donthave_outward_links.adoc obsolete?

### ISSUE THREAD

**Issue by rays22** [ebi-ait/ingest-graph-validator#27]
**Describe the bug**
I think the test [file_donthave_outward_links.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/file_donthave_outward_links.adoc) produces a false error that is due to some recent changes in entity linking by ingest.
**To Reproduce**
1. Run this test on metadata spreadsheet [HealthyAndDiabeticPancreas_GSE101207_ontologies.xlsx]([HealthyAndDiabeticPancreas_GSE101207_ontologies.xlsx](https://drive.google.com/file/d/1CS2VPp_3PfGn_BKYufmDjlnzOR7FfrPi/view?usp=sharing)).
2. **Expected behaviour**
`HealthyAndDiabeticPancreas_GSE101207_ontologies.xlsx` should pass test.
**Screenshots**
>21-01-12 16:36:06 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
21-01-12 16:36:06 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
21-01-12 16:36:06 [ingest_graph_validator.actions.test_action] - INFO: loading tests
21-01-12 16:36:06 [ingest_graph_validator.actions.test_action] - INFO: loaded [19] test queries
21-01-12 16:36:06 [ingest_graph_validator.actions.test_action] - INFO: running tests
21-01-12 16:36:07 [ingest_graph_validator.actions.test_action] - ERROR: test [file_donthave_outward_links.adoc] failed: non-empty result.
21-01-12 16:36:07 [ingest_graph_validator.actions.test_action] - ERROR: result: [{'f': (_32:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818088_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818088_1.fastq.gz', insdc_run_accessions: "['SRR5818088']", read_index: 'read1', schema_type: 'file'})}, {'f': (_33:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818088_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818088_2.fastq.gz', insdc_run_accessions: "['SRR5818088']", read_index: 'read2', schema_type: 'file'})}, {'f': (_34:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818089_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818089_1.fastq.gz', insdc_run_accessions: "['SRR5818089']", read_index: 'read1', schema_type: 'file'})}, {'f': (_35:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818089_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818089_2.fastq.gz', insdc_run_accessions: "['SRR5818089']", read_index: 'read2', schema_type: 'file'})}, {'f': (_36:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818090_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818090_1.fastq.gz', insdc_run_accessions: "['SRR5818090']", read_index: 'read1', schema_type: 'file'})}, {'f': (_37:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818090_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818090_2.fastq.gz', insdc_run_accessions: "['SRR5818090']", read_index: 'read2', schema_type: 'file'})}, {'f': (_38:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818091_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818091_1.fastq.gz', insdc_run_accessions: "['SRR5818091']", read_index: 'read1', schema_type: 'file'})}, {'f': (_39:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818091_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818091_2.fastq.gz', insdc_run_accessions: "['SRR5818091']", read_index: 'read2', schema_type: 'file'})}, {'f': (_40:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818092_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818092_1.fastq.gz', insdc_run_accessions: "['SRR5818092']", read_index: 'read1', schema_type: 'file'})}, {'f': (_41:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818092_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818092_2.fastq.gz', insdc_run_accessions: "['SRR5818092']", read_index: 'read2', schema_type: 'file'})}, {'f': (_42:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818093_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818093_1.fastq.gz', insdc_run_accessions: "['SRR5818093']", read_index: 'read1', schema_type: 'file'})}, {'f': (_43:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818093_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818093_2.fastq.gz', insdc_run_accessions: "['SRR5818093']", read_index: 'read2', schema_type: 'file'})}, {'f': (_44:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818094_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818094_2.fastq.gz', insdc_run_accessions: "['SRR5818094']", read_index: 'read2', schema_type: 'file'})}, {'f': (_45:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR5818094_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR5818094_1.fastq.gz', insdc_run_accessions: "['SRR5818094']", read_index: 'read1', schema_type: 'file'})}, {'f': (_46:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR6313914_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR6313914_1.fastq.gz', insdc_run_accessions: "['SRR6313914']", read_index: 'read1', schema_type: 'file'})}, {'f': (_47:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR6313914_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR6313914_2.fastq.gz', insdc_run_accessions: "['SRR6313914']", read_index: 'read2', schema_type: 'file'})}, {'f': (_48:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR6313915_1.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR6313915_1.fastq.gz', insdc_run_accessions: "['SRR6313915']", read_index: 'read1', schema_type: 'file'})}, {'f': (_49:file:sequence_file {describedBy: 'https://schema.humancellatlas.org/type/file/9.2.0/sequence_file', `file_core.content_description`: "[{'text': 'DNA sequence', 'ontology': 'data:3494', 'ontology_label': 'DNA sequence'}]", 
`file_core.file_name`: 'SRR6313915_2.fastq.gz', `file_core.format`: 'fastq.gz', id: 'SRR6313915_2.fastq.gz', insdc_run_accessions: "['SRR6313915']", read_index: 'read2', schema_type: 'file'})}]
21-01-12 16:36:07 [ingest_graph_validator.actions.test_action] - INFO: all tests finished

**Comment by ESapenaVentura** [comment]
We have decided to delete the test as it's no longer useful
