### ISSUE TITLE
Review all tests to detect outdated/failing tests

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/ingest-graph-validator#29]
Related to #27 but also need to check everything

**Comment by rays22** [comment]
### False graph validation errors
[graph_tests.log](https://github.com/ebi-ait/ingest-graph-validator/files/6477895/graph_tests.log)

Marion and I have found these four false validation errors while running the [graph test set](https://github.com/ebi-ait/ingest-graph-validator/tree/master/graph_test_set) (as of 2021-05-14) on the metadata of [GSE156707 - HumanHeartMaturationsnSeq #298.](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/298)

1. [contains_cell_barcode_info.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/contains_cell_barcode_info.adoc)
    - I think this test should be conditional depending on the `library_preparation_protocol.nucleic_acid_source` value.

> Test description
>When a sequencing protocol is non-10x, non-ss2, test whether metadata is complete.

2. [contains_umi_barcode_info.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/contains_umi_barcode_info.adoc)
    - I think this test should be conditional depending on the `library_preparation_protocol.nucleic_acid_source` value.

>Test description
>When a sequencing protocol is non-10x, non-ss2, test whether metadata is complete.

3. [10x_has_more_than_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/10x_has_more_than_2_files.adoc)
    - I think this test should take into account and check the `sequence_file.lane_index` field before raising an error. 

>Test description
Processes using 10x library preparation protocols have 2 to 4 files linked.

4. [paired_end_2_files.adoc](https://github.com/ebi-ait/ingest-graph-validator/blob/master/graph_test_set/paired_end_2_files.adoc)
 This test has raised false errors when testing dataset <https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/298> .

>Test description
When a sequencing protocol is paired-end, test whether it has 2 or more files linked.
