### ISSUE TITLE
31032021: sequence file file index check

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/ingest-graph-validator#30]
**Describe the issue**

- Test name: sequence file file index check
- Test Description: checks that the number of read1, read2 and index1 files are equal within a group of files with the same cell suspension id and/or process id
- Cypher query:
```
<Fill in a Cypher query or suggest a human-readable test>
```

** Acceptance criteria**

- [ ] The test has been reviewed
- [ ] The test has been implemented into the `graph_test_set` folder

**Comment by ESapenaVentura** [comment]
This is overseeded by the resolution on ticket #11
