### ISSUE TITLE
31032021: check sequence file process id linking

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/ingest-graph-validator#31]
**Describe the issue**

**Test template**

- Test name: 
- Test Description: Check sequence file tab file name is linked to the correct process id  and cell suspension id.
- Cypher query:
```
<Fill in a Cypher query or suggest a human-readable test>
```

** Acceptance criteria**

- [ ] The test has been reviewed
- [ ] The test has been implemented into the `graph_test_set` folder

**Comment by ESapenaVentura** [comment]
I don't understand this test, could you provide with some more information?
