### ISSUE TITLE
Graph validator - Error in files with two library preparation protocols associated

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/ingest-graph-validator#50]
**Describe the bug**
The errors **ensure_seq_libr_prep_protocols.adoc** and **paired_end_2_files.adoc** are given for the files with two library preparation protocols associated to them. 

I tested it also at EC2, and the error **ensure_seq_libr_prep_protocols.adoc** appeared also et EC2, but **paired_end_2_files.adoc** was given only on Ingest.

**ensure_seq_libr_prep_protocols.adoc** appeared error is linked with the files with two library preparation protocols.

**paired_end_2_files.adoc** is related with those files coming from scATAC-seq, which is [paired end](https://teichlab.github.io/scg_lib_structs/methods_html/10xChromium_scATAC.html). Nevertheless, the sequencing protocol is linked to 12 files, so it shouldn't raise the error

The submission is: https://contribute.data.humancellatlas.org/submissions/detail?uuid=85b5d566-bb78-4bed-89e6-2f44e7b6bd48&project=5b328561-4a97-40ac-b7ad-6a90fc59d374

**Comment by ipediez** [comment]
This is the error message I'm getting at EC2 for ensure_seq_libr_prep_protocols.adoc

21-11-23 15:14:58 [ingest_graph_validator.actions.test_action] - ERROR: test [ensure_seq_libr_prep_protocols.adoc] failed: non-empty result.
21-11-23 15:14:58 [ingest_graph_validator.actions.test_action] - ERROR: result: [{'file_name': 'Tcell_activation_day0_HTO_rep1_R1.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day0_HTO_rep1_R2.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1220_RT_HTO_S1_L001_R1_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1220_RT_HTO_S1_L001_R2_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day1_HTO_rep2_R2.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day1_HTO_rep2_R1.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day2_HTO_rep1_R2.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day2_HTO_rep1_R1.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1892_4C_HTO_S1_L001_R2_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1892_4C_HTO_S1_L001_R1_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1892_RT_HTO_S1_L001_R1_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1892_RT_HTO_S1_L001_R2_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day0_HTO_rep2_R2.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': 'Tcell_activation_day0_HTO_rep2_R1.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1472_RT_HTO_S1_L001_R2_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1472_RT_HTO_S1_L001_R1_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1472_4C_HTO_S1_L001_R2_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}, {'file_name': '1472_4C_HTO_S1_L001_R1_001.fastq.gz', 'message': 'ERROR:  missing sequencing or library preparation protocol.'}]

**Comment by ESapenaVentura** [comment]
I believe this is solved so closing!
