### ISSUE TITLE
Remove or change contains_cell_barcode_info.adoc test

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/ingest-graph-validator#57]
I think we need to change or remove the cell barcode test. I'm requesting this because I'm submitting a sci-CAR ATAC-seq dataset that doesn't contain cell barcodes it uses a series of barcodes in the indexes to identify individual cells which do not fit our current description for cell barcodes.

**Comment by ESapenaVentura** [comment]
Change is in dev now
