### ISSUE TITLE
Improve smartseq2_has_2-3_files to allow 1 fastq if the sequencing is single ended

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/ingest-graph-validator#62]
**Describe the bug**
The graph validator raises the smartseq2_has_2-3_files error even if the sequencing is single-ended

**To Reproduce**
1. Upload a submission in ingest with:
   -  Library preparation: SmartSeq2 
   -  Sequencing protocol: single end
   - One fastq file per plate well

2. Click on Validate submission
3. See error

**Desired behavior**
For SmartSeq2 if the sequencing is single-ended the graph validator should allow to have one fastq per process, without raising an error.

Already discussed with @ESapenaVentura

**Comment by ofanobilbao** [comment]
Blocking https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/535
