### ISSUE TITLE
20200514: edit sequence_file_linkto_cell_suspesion test

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/ingest-graph-validator#8]
**Describe the issue**

I noticed that there is a rule in the test set that says all sequence files should link to a cell suspension, but this is not a strict rule. I would ideally like this rule to throw and error with a summary that shows for which entities this is the case rather than failing validation. The specific project this is relevant for at the moment is the TissueSensitivity project but it is also possible that there could be more data in the future that would fail this test.

The specific test file is:
graph_test_set/sequence_file_linkto_cell_suspesion.adoc

** Acceptance criteria**

- [ ] The test has been reviewed
- [ ] The test has been implemented into the `graph_test_set` folder

**Comment by mshadbolt** [comment]
@ESapenaVentura had the idea to create a more complex version of the test where the test only runs if the input is single cell or single nuclei.

**Comment by ESapenaVentura** [comment]
This was addressed on PR https://github.com/ebi-ait/ingest-graph-validator/pull/34

Closing now!
